import Sidebar from '@/components/common/Sidebar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko' className={inter.className}>
      <body className='flex '>
        <Sidebar />
        <main className='w-full'>{children}</main>
      </body>
    </html>
  );
}
